[
    {
        "id": 229376107,
        "name": "django_cve_2019_19844_poc",
        "full_name": "ryu22e\/django_cve_2019_19844_poc",
        "owner": {
            "login": "ryu22e",
            "id": 301892,
            "avatar_url": "https:\/\/avatars1.githubusercontent.com\/u\/301892?v=4",
            "html_url": "https:\/\/github.com\/ryu22e"
        },
        "html_url": "https:\/\/github.com\/ryu22e\/django_cve_2019_19844_poc",
        "description": "PoC for CVE-2019-19844(https:\/\/www.djangoproject.com\/weblog\/2019\/dec\/18\/security-releases\/)",
        "fork": false,
        "created_at": "2019-12-21T04:30:34Z",
        "updated_at": "2019-12-25T03:07:48Z",
        "pushed_at": "2019-12-24T12:31:47Z",
        "stargazers_count": 14,
        "watchers_count": 14,
        "forks_count": 0,
        "forks": 0,
        "watchers": 14,
        "score": 0
    }
]